# Generated by Django 3.0.7 on 2020-07-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200626_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
