# Generated by Django 3.0.7 on 2020-07-01 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_whattoknow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'video'), ('other', 'other')], max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.ContentType'),
            preserve_default=False,
        ),
    ]
